### PR TITLE
Compilation of different sources of information

### PR DESCRIPTION
**Pull request by llemeurfr**
I used the content of the requirements.md document prepared by Hadrien (master branch), the items detailed on https://webpub-protect.herokuapp.com/app/ by Daniel and the "Requirements for web contents protection in web browser" written by Taehyun in a consistent set of documents:

introduction.md as an introduction to the project
problems.md as a detail of the list of aspects of Web content which allow over-sharing of Web Publications
solutions.md as  proposed solutions for limiting copy of Web Publications

### CODE REVIEW

**Comment by HadrienGardeur** [comment]
Is this the right place for this document though? Could we host this on https://github.com/readium/web instead?

**Comment by llemeurfr** [comment]
Pas faux. I have left the documents where you started adding requirements, but indeed /web is a better place.

**Comment by HadrienGardeur** [comment]
Yeah but the "other" folder is a bit of a dead-end that we eventually want to get rid of. We didn't had a proper web repo when we initiated these discussions. Since this is Readium Web specific IMO, it feels better suited to host it in that repo.

**Comment by llemeurfr** [comment]
Are you ok for /web/docs/protection then?

**Pull request closed without merging**
