### PR TITLE
Init origin issue

### PR DESCRIPTION
**Pull request by JayPanoz**
Note: this is the best I could init with the multiple sources I had at hand so sorry in advance if the outline is what it currently is, I wanted to make it available ASAP while emphasising this is a draft that will evolve over the next months. 

@HadrienGardeur That also means I’d be completely fine reworking the doc on my fork until we deem it “pullable” into the (more public) Readium Repo. 

I’m also willing to work with (test) app implementers to fill in the current gaps. So that’s @aferditamuriqi (iOS, Android, web), @danielweck (desktop) and @jccr (web). 

I am really not asking that you commit extra info in documentation form; discussions, comments, notes, pointing out some links, etc. will be absolutely OK – which is also the reason why I explicitly put myself as “editor” at the very top so that this doc doesn’t bring additional work on your plates. 

Once again, that’s I hope a consistent whole resulting from various sources, including specs, issues in other repos, Dan’s and our private docs so I know there’s a lot of room for improvement. I may also add details at a later date because I tried to focus on getting a global and not platform-specific low-level explainer. 

On a related note, please feel free to ask the source of the illustrations (it is an illustrator file though, but I can export it to SVG.)

### CODE REVIEW

**Comment by ErikHellman** [comment]
When I've done similar solutions before, e.g., displaying local content in a WebView inside an app (Android), I used to override the requests and deliver the content without an HTTP server. 

Technically, this is done by overriding the function `WebViewClient.shouldInterceptRequest()` and return a `WebResourceResponse` with the content we want to deliver to the WebView. Basically, we create an in-app proxy. The WebView won't be able to tell that the response isn't coming from a "real" web server, and we can deliver data in the same way as an HTTP server. The only exception is Web Sockets which cannot be handled by this.

This effectively eliminates the problems with same-origin policy, server-port issues, and any security concerns there might be with having an open socket that anyone on the same network can connect to. Another advantage of this is that we reduce the memory consumption and the performance of loading content in the WebView will be significantly improved.

This also means that we can use any valid HTTP/HTTPS base URL, like `https://localhost:12345/`, without risking any conflicting ports, and at the same time have a single origin for all device-local content that is loaded by the WebView.

This approach should be possible on all native platforms, although I haven't tested this on iOS or Desktop myself.

For further details, please see the API documentation for [WebViewClient.shouldInterceptRequest()](https://developer.android.com/reference/android/webkit/WebViewClient.html#shouldInterceptRequest(android.webkit.WebView,%20android.webkit.WebResourceRequest)).

**Comment by JayPanoz** [comment]
@ErikHellman Thank you very much, this is exactly the type of feedback/comment that will help improve this doc. 👍 

I’ll take a look ASAP as the “solutions part” is currently lacking. 

For desktop, at least in Electron, Daniel [has documented his solution here](https://github.com/readium/r2-streamer-js/blob/develop/docs/origin.md#electron) (custom scheme).

We’ve had a super quick discussion on the Android side [following the Android Dev Summit](https://www.youtube.com/watch?v=HGZYtDZhOEQ&amp;t=0s&amp;index=30), which actually triggered this doc to some extent so once again thank you very much for pointing out possible solutions!

**Comment by ErikHellman** [comment]
@JayPanoz Thanks! That talk from ADS is really good. Note that he recommends against using custom schemes as it breaks app behaviour, and explicitly says that one should use "your own domain" as the base URL when loading in-app data. This recommendation applies to desktop and iOS as well, since the "breaking app behaviour" he mentions relates to how the web works and not Android specifically.

One of the "new" APIs for Android that I need to test in our case is `loadDataWithBaseURL()`. If I interpret this correctly and it turns out it works, I believe we can use that for injecting JavaScript and CSS without having to modify the original content. We load the Readium CSS and JS using this function, as well as a small piece of JS code that will modify the DOM and insert the content. This would significantly reduce the need to do any "server-side" parsing of the content. The same should be possible on iOS using [evaluateJavaScript()](https://developer.apple.com/documentation/webkit/wkwebview/1415017-evaluatejavascript).

**Comment by ErikHellman** [comment]
@JayPanoz After chatting with a friend I was recommended the following; https://developers.google.com/web/updates/2018/06/feature-policy

I think this would be a way forward regarding the origins problem for the web.

**Comment by JayPanoz** [comment]
Thanks! I came across this one yesterday I think, via Smashing Magazine, but couldn’t give it a proper look as I was writing down the doc so this is definitely on my to-test list.

For reference, [the canIuse](https://caniuse.com/#search=feature%20policy)

**Comment by ErikHellman** [comment]
Another implementation detail for Android on this topic: https://github.com/google/webview-local-server

This is the recommended solution by Google for how to serve content that is either in-app (such as the Readium CSS, fonts and JS) or local files on the device (epub files).

**Comment by HadrienGardeur** [comment]
Merging and closing this PR, let's continue discussions in the issue tracker.

**Pull request merged**
