### PR TITLE
Merge Format into MediaType

### PR DESCRIPTION
**Pull request by mickael-menu**
* `Format` got merged into `MediaType`, to simplify the media type APIs.
  * You can use `MediaType.of()` to sniff the type of a file or bytes.
  * `MediaType` has now optional `name` and `fileExtension` properties.
  * Some publication formats can be represented by several media type aliases. Using `mediaType.canonicalized` will give
    you the canonical media type to use, for example when persisting the file type in a database. All Readium APIs are
    already returning canonical media types, so it only matters if you create a `MediaType` yourself from its string
    representation.

### CODE REVIEW

**Review by qnga — APPROVED** [review]
Great, that's better this way.

Just one thing that was already here in the previous version: I'm not sure readFileSignature should decode bytes and return a String. Generally speaking, a magic number is a sequence of bytes, not necessarily a string. In the worst case, it might not make sense in any encoding. What do you think of it?

**Comment by mickael-menu** [comment]
> Just one thing that was already here in the previous version: I'm not sure readFileSignature should decode bytes and return a String. Generally speaking, a magic number is a sequence of bytes, not necessarily a string. In the worst case, it might not make sense in any encoding. What do you think of it?

You have a point, I'll update the proposal. I returned a string to make ASCII-based magic number (e.g. `%PDF`) more visible, but it can still be done on the client side of this API.

**Comment by mickael-menu** [comment]
Although the API looks a bit contrived now: `readFileSignature(length: Int) -> ByteArray?`.

I think we might as well remove it and introduce `read(range) -> ByteArray?` instead.

**Comment by qnga** [comment]
Sounds good!

**Review by aferditamuriqi — APPROVED** [review]

**Pull request merged**
